export interface NQ { id: string; q: string; hint?: string }
export interface NSection { id: string; title: string; intro?: string; questions: NQ[] }

export const GENERAL_SECTIONS: NSection[] = [
  { id: "A", title: "A. Department Profile", questions: [
    { id: "A1", q: "Department Name" },
    { id: "A2", q: "Respondent Full Name" },
    { id: "A3", q: "Position / Official Designation" },
    { id: "A4", q: "Years in Current Role" },
    { id: "A5", q: "Primary mandate and responsibilities of your department", hint: "What is your department officially charged to do within NESREA?" },
    { id: "A6", q: "Total number of staff (including zonal/field staff)" },
    { id: "A7", q: "States or zones your department covers or supervises" },
    { id: "A8", q: "Sub-units or divisions (list and briefly describe each)" },
    { id: "A9", q: "Who do you report to, and which departments do you interact with?" },
    { id: "A10", q: "Single most important contribution to NESREA's overall mandate" },
  ]},
  { id: "B", title: "B. Current Operations", questions: [
    { id: "B1", q: "Major functions performed by your department", hint: "E.g., permits, inspections, EIAs, prosecutions" },
    { id: "B2", q: "Key services delivered to external stakeholders" },
    { id: "B3", q: "Regular workflows (monthly, weekly, daily)" },
    { id: "B4", q: "Approvals managed or granted, and approval authority" },
    { id: "B5", q: "Reports generated and recipients (name, frequency, recipient)" },
    { id: "B6", q: "Data collected during routine operations" },
    { id: "B7", q: "Frequency of data collection (daily/weekly/monthly/per-event)" },
    { id: "B8", q: "Tools, software, or systems currently used" },
    { id: "B9", q: "Activities still entirely paper-based" },
    { id: "B10", q: "Activities already digitized (even partially)" },
  ]},
  { id: "C", title: "C. Workflow Analysis", intro: "Answer for your department's MOST IMPORTANT workflow.", questions: [
    { id: "C1", q: "End-to-end workflow of your department's primary function" },
    { id: "C2", q: "What triggers this workflow?" },
    { id: "C3", q: "Internal units/departments that participate" },
    { id: "C4", q: "Documents generated at each stage" },
    { id: "C5", q: "Approvals required, and who provides each" },
    { id: "C6", q: "Average workflow duration (best, typical, worst case)" },
    { id: "C7", q: "Stages that consistently cause delays" },
    { id: "C8", q: "Root causes of those delays" },
    { id: "C9", q: "Information frequently difficult or impossible to obtain" },
    { id: "C10", q: "Tasks that consume the most staff time (and any that could be automated)" },
  ]},
  { id: "D", title: "D. Data & Information Management", questions: [
    { id: "D1", q: "Data most critical to your department" },
    { id: "D2", q: "Where this critical data is stored today" },
    { id: "D3", q: "How data is collected — by whom, method, and stage" },
    { id: "D4", q: "How data is verified for accuracy" },
    { id: "D5", q: "How data is shared within NESREA" },
    { id: "D6", q: "How data is shared with external parties" },
    { id: "D7", q: "Biggest reporting challenges" },
    { id: "D8", q: "Information you wish you had in real time" },
    { id: "D9", q: "Data that would lead to significantly better management decisions" },
    { id: "D10", q: "Data collection activities duplicated across departments" },
  ]},
  { id: "E", title: "E. Challenges & Bottlenecks", intro: "Responses are confidential. Honest answers produce a better platform.", questions: [
    { id: "E1", q: "Top five operational challenges" },
    { id: "E2", q: "Main causes of service delivery delays" },
    { id: "E3", q: "Compliance challenges with regulated entities" },
    { id: "E4", q: "Monitoring challenges" },
    { id: "E5", q: "Enforcement challenges" },
    { id: "E6", q: "Reporting challenges (internal and upward)" },
    { id: "E7", q: "Stakeholder engagement challenges" },
    { id: "E8", q: "Technology-related challenges" },
    { id: "E9", q: "Risks of current manual/paper-based processes" },
    { id: "E10", q: "Activities most vulnerable to manipulation or interference (confidential)" },
  ]},
  { id: "F", title: "F. Technology Assessment", questions: [
    { id: "F1", q: "Software systems, digital tools, or platforms used" },
    { id: "F2", q: "Are any of these systems integrated? Describe how." },
    { id: "F3", q: "Information entered into multiple systems separately" },
    { id: "F4", q: "Manual/paper processes to prioritize for automation" },
    { id: "F5", q: "Reports that should be auto-generated" },
    { id: "F6", q: "Approvals that should be digitized" },
    { id: "F7", q: "Inspections / field activities for a mobile digital tool" },
    { id: "F8", q: "External systems / databases NESREA ONE should integrate with" },
    { id: "F9", q: "Connectivity challenges in field / zonal offices" },
    { id: "F10", q: "One technology solution that would have the greatest impact tomorrow" },
  ]},
  { id: "G", title: "G. Executive Intelligence Requirements", intro: "The DG Command Center will be built directly from this section.", questions: [
    { id: "G1", q: "Information leadership most frequently requests from your department" },
    { id: "G2", q: "Information that takes the longest to compile" },
    { id: "G3", q: "Information that should be instantly available to the DG" },
    { id: "G4", q: "Daily performance indicators management should monitor" },
    { id: "G5", q: "National environmental indicators to monitor continuously" },
    { id: "G6", q: "Compliance indicators to monitor nationally" },
    { id: "G7", q: "Operational indicators for departmental performance" },
    { id: "G8", q: "Dashboard / visual display that would best aid decisions" },
    { id: "G9", q: "Alerts management should receive automatically" },
    { id: "G10", q: "Predictive information that would help leadership plan" },
  ]},
  { id: "H", title: "H. Future State", questions: [
    { id: "H1", q: "Three major problems technology should solve" },
    { id: "H2", q: "Ideal fully-digital version of your department in five years" },
    { id: "H3", q: "Services citizens should access entirely online" },
    { id: "H4", q: "Services businesses should access online" },
    { id: "H5", q: "Processes that should become fully paperless within 12 months" },
    { id: "H6", q: "Information that should be made publicly accessible" },
    { id: "H7", q: "Information that should remain restricted" },
    { id: "H8", q: "New environmental intelligence capabilities to develop" },
    { id: "H9", q: "Single innovation that would most improve outcomes" },
    { id: "H10", q: "What success looks like three years after platform launch" },
  ]},
  { id: "I", title: "I. Priority Ranking", intro: "Rank 1 (highest) to 10 (lowest), each number used once. Then explain.", questions: [
    { id: "I_rank", q: "Provide your ranking 1-10 for: Environmental Monitoring; Citizen Reporting; Compliance & GreenScore; EIA & Permit Portal; Enforcement & Case Mgmt; Data & Analytics; Climate Finance; DG Command Center; Mobile Field Inspection; AI Regulatory Assistance" },
    { id: "I_top3", q: "Explain your top three priorities — why are these most critical?" },
    { id: "I_missing", q: "Any critical capabilities not listed?" },
  ]},
];

export interface DeptDef { code: string; label: string; questions: NQ[] }

export const DEPARTMENTS: DeptDef[] = [
  { code: "EIA-DEPT", label: "Environmental Assessment & Permits", questions: [
    { id: "EIA1", q: "EIA applications received per month/year on average" },
    { id: "EIA2", q: "Walk through the EIA review process from submission to final decision" },
    { id: "EIA3", q: "Most common reasons EIA applications are delayed, returned, or rejected" },
    { id: "EIA4", q: "Documents required for a full EIA submission" },
    { id: "EIA5", q: "How public notices are managed during the EIA review" },
    { id: "EIA6", q: "How permits are issued and authenticity verified" },
    { id: "EIA7", q: "Estimated % of permits expiring without renewal, and how tracked" },
    { id: "EIA8", q: "How permit conditions are monitored after issuance" },
    { id: "EIA9", q: "Fee structures for EIA processing and permits; payment methods" },
    { id: "EIA10", q: "What a fully digital EIA portal would need to replace the paper process" },
  ]},
  { code: "ENF-DEPT", label: "Enforcement & Compliance", questions: [
    { id: "ENF1", q: "Currently open enforcement cases" },
    { id: "ENF2", q: "Full enforcement case lifecycle (detection -> resolution)" },
    { id: "ENF3", q: "Average time from violation detection to penalty issuance" },
    { id: "ENF4", q: "How evidence is collected and stored today" },
    { id: "ENF5", q: "% of issued penalties actually collected; what happens to the rest" },
    { id: "ENF6", q: "Most common violation types and worst-offending sectors" },
    { id: "ENF7", q: "Biggest obstacles to successful prosecution" },
    { id: "ENF8", q: "How inspectors communicate findings from field to HQ" },
    { id: "ENF9", q: "What a digital enforcement case management system must include" },
    { id: "ENF10", q: "Highest-risk companies/sectors nationally and how risk is assessed" },
  ]},
  { code: "MON-DEPT", label: "Environmental Monitoring & Surveillance", questions: [
    { id: "MON1", q: "Parameters monitored (air, water, soil, noise, radiation)" },
    { id: "MON2", q: "Monitoring equipment/sensors and locations" },
    { id: "MON3", q: "How monitoring data is collected, transmitted, stored" },
    { id: "MON4", q: "Frequency and geographic coverage of monitoring" },
    { id: "MON5", q: "Monitoring gaps (parameters / zones / frequency)" },
    { id: "MON6", q: "Use of satellite or remote sensing data" },
    { id: "MON7", q: "How monitoring results trigger enforcement/advisory" },
    { id: "MON8", q: "Baseline environmental data for Nigeria and where stored" },
    { id: "MON9", q: "What a national real-time monitoring dashboard must show" },
    { id: "MON10", q: "Highest-risk parameters needing urgent monitoring improvement" },
  ]},
  { code: "CIT-DEPT", label: "Public Affairs & Citizen Engagement", questions: [
    { id: "CIT1", q: "Citizen complaints / environmental reports per month" },
    { id: "CIT2", q: "Channels through which complaints are received" },
    { id: "CIT3", q: "End-to-end complaint resolution process" },
    { id: "CIT4", q: "Average time from receipt to first action; to full resolution" },
    { id: "CIT5", q: "% of complaints resulting in inspection / violation / penalty" },
    { id: "CIT6", q: "How complainants are notified of status and outcome" },
    { id: "CIT7", q: "What prevents more citizens from reporting violations" },
    { id: "CIT8", q: "Existing mechanisms for proactive public communication" },
    { id: "CIT9", q: "Information about NESREA's work citizens most frequently request" },
    { id: "CIT10", q: "What a citizen reporting platform must do to dramatically increase valid reports" },
  ]},
  { code: "LEG-DEPT", label: "Legal & Prosecution", questions: [
    { id: "LEG1", q: "Active prosecution cases" },
    { id: "LEG2", q: "Average time from referral to first court appearance" },
    { id: "LEG3", q: "Evidence typically required to successfully prosecute" },
    { id: "LEG4", q: "Most common reasons cases are lost or withdrawn" },
    { id: "LEG5", q: "How legal documents, case files, court orders are stored/managed" },
    { id: "LEG6", q: "Process for issuing and tracking administrative penalty notices" },
    { id: "LEG7", q: "Legal instruments most frequently cited in prosecutions" },
    { id: "LEG8", q: "What a digital legal case management system must include" },
    { id: "LEG9", q: "Digital evidence capabilities that would strengthen prosecutorial capacity" },
    { id: "LEG10", q: "Active-case information the DG should see in real time" },
  ]},
  { code: "ICT-DEPT", label: "ICT & Data Management", questions: [
    { id: "ICT1", q: "Current IT infrastructure (servers, connectivity, devices, network)" },
    { id: "ICT2", q: "Software systems deployed agency-wide" },
    { id: "ICT3", q: "State of internet connectivity at HQ and zonal offices" },
    { id: "ICT4", q: "Biggest cybersecurity risks / vulnerabilities" },
    { id: "ICT5", q: "Data backup and disaster recovery procedures" },
    { id: "ICT6", q: "Integration capabilities with external government platforms" },
    { id: "ICT7", q: "Current database architecture for operational data" },
    { id: "ICT8", q: "Device availability for field staff" },
    { id: "ICT9", q: "Primary constraints for new digital platform deployment" },
    { id: "ICT10", q: "Technical standards / policies the platform must comply with" },
  ]},
  { code: "FIN-DEPT", label: "Finance & Administration", questions: [
    { id: "FIN1", q: "Main revenue streams (permit fees, fines, penalties, others)" },
    { id: "FIN2", q: "How permit fees and penalty payments are collected and receipted" },
    { id: "FIN3", q: "Process for tracking outstanding penalties and ensuring collection" },
    { id: "FIN4", q: "Total estimated value of uncollected penalties" },
    { id: "FIN5", q: "Procurement processes for platform/technology acquisition" },
    { id: "FIN6", q: "Financial reporting produced and frequency" },
    { id: "FIN7", q: "Departmental budget planning and performance tracking" },
    { id: "FIN8", q: "Financial controls and expenditure authorization workflows" },
    { id: "FIN9", q: "Financial information the DG should see in real time" },
    { id: "FIN10", q: "Revenue improvement opportunities from digitization" },
  ]},
  { code: "RES-DEPT", label: "Planning, Research & Statistics", questions: [
    { id: "RES1", q: "Research and data collection activities" },
    { id: "RES2", q: "National environmental databases / registries maintained" },
    { id: "RES3", q: "Statistical publications / reports and frequency" },
    { id: "RES4", q: "Current gaps in Nigeria's national environmental data" },
    { id: "RES5", q: "How the annual State of Environment Report is compiled and time required" },
    { id: "RES6", q: "Data from other agencies (NIMET, NBS, NUPRC, NAFDAC) to integrate" },
    { id: "RES7", q: "Research partnerships (universities, international, NGOs)" },
    { id: "RES8", q: "Indicators Nigeria should report to international bodies but currently cannot" },
    { id: "RES9", q: "What a national environmental data warehouse must contain" },
    { id: "RES10", q: "Predictive models / early warning systems NESREA should develop" },
  ]},
];

export const FINAL_SECTION: NSection = {
  id: "Z", title: "Final: Open Recommendations", questions: [
    { id: "Z1", q: "Additional observations, concerns, risks, or opportunities" },
    { id: "Z2", q: "Any process/system you believe is fundamentally broken and must be redesigned (not just digitized)" },
    { id: "Z3", q: "If you were DG for a day, what is the first digital system you would build and why?" },
  ],
};
